package org.lilradish.lite.app.listing

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres
import java.sql.Connection
import javax.sql.DataSource
import org.lilradish.lite.testutil.Baseline
import org.springframework.jdbc.core.simple.JdbcClient
import org.springframework.jdbc.datasource.SingleConnectionDataSource
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification

/**
 * The one fold, held level on both sides it is applied to. Held text is folded once, when its row is
 * written, into a column the store generates; what a reader typed is folded when a search runs. Two
 * definitions of the fold would drift apart without any search failing loudly — names would simply
 * stop being found — so both sides are asked here of what the store itself holds.
 *
 * <p>The stored folds are discovered from the catalogue rather than listed, so a fold added to another
 * table is judged by the same rule the moment it exists. Rows a feature writes are rolled back.
 */
class SearchFoldingIntegrationSpec extends Specification {

    static final String COMBINING_ACUTE = Character.toString(0x0301)

    @Shared
    @AutoCleanup
    EmbeddedPostgres server = EmbeddedPostgres.builder().start()

    @Shared
    DataSource database

    def setupSpec() {
        database = Baseline.appliedTo(server, "postgres")
    }

    /**
     * Stored and virtual alike, because PostgreSQL 18 makes a column virtual unless it says STORED, and a
     * virtual one may call no user function: a fold there could only be a second copy of search_fold.
     */
    def "a generated column is a stored fold exactly where its name says so, by the function a search folds what was typed with"() {
        when:
        def session = JdbcClient.create(database)
        def generated = session.sql("""
                select table_of.relname || '.' || folded.attname as stored,
                       pg_get_expr(generation.adbin, generation.adrelid) as expression
                  from pg_attribute folded
                  join pg_class table_of on table_of.oid = folded.attrelid
                  join pg_attrdef generation
                    on generation.adrelid = folded.attrelid and generation.adnum = folded.attnum
                 where table_of.relnamespace = 'app'::regnamespace and folded.attgenerated <> ''
                """).query { row, number -> [row.getString("stored"), row.getString("expression")] }.list()
                .collectEntries()
        def notStored = session.sql("""
                select table_of.relname || '.' || folded.attname
                  from pg_attribute folded
                  join pg_class table_of on table_of.oid = folded.attrelid
                 where table_of.relnamespace = 'app'::regnamespace and table_of.relkind in ('r', 'p')
                   and folded.attnum > 0 and not folded.attisdropped
                   and folded.attname like '%\\_folded' and folded.attgenerated <> 's'
                """).query(String).list()
        def folds = generated.findAll { it.key.endsWith("_folded") }
        def others = generated.findAll { !it.key.endsWith("_folded") }

        then:
        folds.every { column, expression -> expression == "search_fold(${column.split("\\.", 2)[1] - ~/_folded$/})" }

        and: "every column named as a fold is stored, so none is written by hand or computed as it is read"
        notStored.isEmpty()

        and: "no column named otherwise folds anything"
        others.values().every { !it.contains("search_fold(") }

        and: "judged over folds and over other generated columns that both exist"
        !folds.isEmpty()
        !others.isEmpty()

        and: "the function every fold is generated by is the one a search applies to what was typed"
        SearchFolding.holds("held", ":typed").contains("(select search_fold(:typed))")
    }

    /**
     * Written one way and typed another — decomposed or composed, in either case, a letter folding to
     * two — the text typed whole or in part finds the name stored.
     */
    def "a name is found by what was typed however either side spelt its accents or cased its letters"() {
        expect:
        finds(stored, typed)

        where:
        stored                                   | typed
        "E" + COMBINING_ACUTE + "mile Zola"       | "émile zola"
        "Émile Zola"                              | "E" + COMBINING_ACUTE + "MILE"
        "Straße"                                  | "STRASSE"
        "grace hopper"                            | "GRACE HOPPER"
        "山田　太郎"                                  | "田　太"
    }

    /**
     * The fold is canonical and not compatible, and Unicode's default rather than Turkish: an accent
     * typed bare, a full-width letter typed plain, and a dotted capital I typed as a plain i each find
     * nothing, which is accepted.
     */
    def "a name is not found by text only a looser fold would take for it"() {
        expect:
        !finds(stored, typed)

        where:
        stored       | typed
        "René"       | "Rene"
        "Ａda"        | "Ada"
        "İpek"       | "ipek"
        "Émile Zola" | "Emile"
    }

    private boolean finds(String stored, String typed) {
        Connection connection = database.connection
        connection.autoCommit = false
        try {
            def session = JdbcClient.create(new SingleConnectionDataSource(connection, true))
            session.sql("insert into people (user_id, display_name) values ('000901', ?)").param(stored).update()
            session.sql("select count(*) from people where ${SearchFolding.holds('display_name_folded', ':typed')}")
                    .param("typed", typed).query(Long).single() == 1
        } finally {
            connection.rollback()
            connection.close()
        }
    }
}
