import { ThemeProvider } from "@mui/material/styles";
import { render, screen } from "@testing-library/react";
import type { ReactNode } from "react";
import { describe, expect, it } from "vitest";

import { theme } from "../theme/theme";
import { GeneratedOutput } from "./GeneratedOutput";

/** `theme.palette.generated.main`, as a resolved colour is reported back. */
const MARK_COLOUR = "rgb(91, 63, 168)";

/**
 * Rendered under the real theme, because an `sx` value is not type-checked
 * against the property it is written on: a misspelt one still compiles, and
 * an unresolved palette path is emitted verbatim as invalid CSS and dropped.
 * Only a rendered colour distinguishes either from a working mark.
 */
function themed(children: ReactNode) {
  return render(<ThemeProvider theme={theme}>{children}</ThemeProvider>);
}

describe("GeneratedOutput", () => {
  it("shows the model's words and says whose they are", () => {
    themed(<GeneratedOutput text="the model said this" />);

    expect(screen.getByText("Generated by a model")).toBeVisible();
    expect(screen.getByText("the model said this")).toBeVisible();
  });

  /**
   * The rule down the edge is the half of the mark that survives a long output
   * scrolling the words out of view, so it has to carry the token rather than
   * inherit the text colour the way an uncoloured border shorthand would.
   */
  it("draws the mark and its rule in the generated colour", () => {
    themed(<GeneratedOutput text="a token" />);

    const region = screen.getByRole("region");
    const mark = screen.getByText("Generated by a model");

    expect(getComputedStyle(mark).color).toBe(MARK_COLOUR);
    expect(getComputedStyle(region).borderLeftColor).toBe(MARK_COLOUR);
  });

  /**
   * The mark cannot wait for content: the region fills in as tokens land, and
   * a mark that appears with the first token is a mark that was missing.
   */
  it("marks the region before a single token has arrived", () => {
    const { container } = themed(<GeneratedOutput text="" />);

    expect(screen.getByText("Generated by a model")).toBeVisible();
    expect(container.querySelector("output")).toBeEmptyDOMElement();
  });

  /**
   * `output` maps to role=status, which implies both aria-live polite and
   * aria-atomic true — together, the whole output read from the top on every
   * change. The element stays for what it says the region is; the announcing
   * that comes with it is switched off.
   */
  it("keeps the live region the output element implies switched off", () => {
    const { container } = themed(<GeneratedOutput text="a token" />);
    const output = container.querySelector("output");

    expect(output?.getAttribute("aria-live")).toBe("off");
    expect(output).toHaveTextContent("a token");
  });

  /**
   * A named `section` maps to the region landmark, so the mark is what someone
   * moving between landmarks hears before reading a word of the output.
   */
  it("names the region with the mark rather than leaving the mark loose", () => {
    themed(<GeneratedOutput text="a token" />);

    const region = screen.getByRole("region");

    expect(region.tagName).toBe("SECTION");
    expect(region).toHaveAccessibleName("Generated by a model");
  });

  /**
   * A step shows output still arriving beside output already recorded. A fixed
   * id would make both regions resolve their label to the first one's mark,
   * leaving the second named by a mark that is not in it.
   */
  it("gives each region its own mark when a page shows two", () => {
    themed(
      <>
        <GeneratedOutput text="arriving" />
        <GeneratedOutput text="recorded" />
      </>,
    );

    const [live, stored] = screen.getAllByRole("region");

    expect(live).toHaveAccessibleName("Generated by a model");
    expect(stored).toHaveAccessibleName("Generated by a model");
    expect(live.getAttribute("aria-labelledby")).not.toBe(
      stored.getAttribute("aria-labelledby"),
    );
  });

  it("renders what a model wrote as text, never as markup", () => {
    themed(<GeneratedOutput text="<script>alert(1)</script>" />);

    expect(screen.getByText("<script>alert(1)</script>")).toBeVisible();
    expect(document.querySelector("script")).toBeNull();
  });

  /**
   * A model's line breaks carry its meaning — a list stays a list — and the
   * default `white-space` renders every one of them as a space. It takes both
   * assertions to say so: `textContent` is the concatenated data of the text
   * nodes, which no rendering property can reach, so it shows the breaks
   * arrived but never that they survive being drawn.
   */
  it("renders a model's line breaks instead of collapsing them into spaces", () => {
    const { container } = themed(
      <GeneratedOutput text={"line one\n\nline two"} />,
    );
    const [output] = container.getElementsByTagName("output");

    expect(output.textContent).toBe("line one\n\nline two");
    expect(getComputedStyle(output).whiteSpace).toBe("pre-wrap");
  });
});
