/**
 * Every sentence this side owns, in the language it was written in.
 *
 * Ids say what a sentence is about rather than where it appears: the same words
 * are shown by several screens, and an id naming one of them is wrong on the
 * rest.
 *
 * The two catalogues split on one mechanical rule: an id is `LIB_EN` when a
 * module under `lib/` says it, and `APP_EN` otherwise. Nothing under `lib/` may
 * reach into the business half, so what it says has to be sayable without one.
 * The prefix names the topic and not the side — `navigation.breadcrumb` is a
 * control, `navigation.site` is this application's own shape.
 */
export const LIB_EN = {
  /** A time today or yesterday, where the day is said in words. */
  "when.relative": "{time} {day}",
  /** A time further back, where the day is a date. */
  "when.dated": "{date} {time}",
  /** How many things of one kind are waiting on the reader. */
  "task.waiting": "{count} waiting",
  /** Said of a whole kind of waiting work, never of any one of them. */
  "task.urgent": "Urgent",
  /** Stands where an answer will go, for as long as the read is still out. */
  "read.pending": "Still reading…",
  /** Marks text a model wrote, as against the system's own words. */
  "output.generated": "Generated by a model",
  /** Names the trail back through the screens already passed; never drawn. */
  "navigation.breadcrumb": "Breadcrumb",
  /** Names the control that shows the steps of a trail too long to show whole. */
  "navigation.wholeTrail": "Show the whole trail",
  /** A met expectation, read immediately before the name it is a verdict on. */
  "verdict.pass": "pass",
  /** An unmet one, read in the same place and weighed against its opposite. */
  "verdict.fail": "fail",

  /**
   * Moving through a collection. Neither names a position in it, because a
   * cursor gives none: there is the start, and there is whatever comes after
   * what is in hand.
   */
  "paging.first": "First page",
  "paging.next": "Next page",
  /** Shuts what is read about one row where it covers the list it was opened from. */
  "panel.close": "Close",
  /** Names the matches a search offers, of which the reader picks one. */
  "search.matches": "Matches",
  /** How many a search found, where every one of them is shown. */
  "search.found": "{count} found",
  /** A search found more than it shows; narrowing it is the way to the rest. */
  "search.more":
    "More were found than the {count} shown. Type more to narrow them down.",
};

export const APP_EN = {
  /**
   * Names the landmark holding every destination; never drawn. Not "Site
   * navigation", which a screen reader reads out as "Site navigation
   * navigation" — the role is announced already and is not part of the name.
   */
  "navigation.site": "Site",
  /** Jumps a keyboard past the destinations to the work itself. */
  "navigation.skip": "Skip to content",
  /** The control that brings the destinations out on a narrow viewport. */
  "navigation.open": "Open navigation",

  /**
   * The places a person can go. Which group each belongs to and what order they
   * come in are not here: a catalogue that carried them would be where the shape
   * of the navigation lived, and translating it would be editing that shape.
   */
  "destination.people": "People",
  /** The groups work is done in, not the people standing in any one of them. */
  "destination.groups": "Groups",
  /** How much of what each group owns still holds together, as of the last check. */
  "destination.soundness": "Soundness",
  "destination.measurements": "Measurements",
  "destinationGroup.system": "System management",
  /** What waits on the reader in every group they are in, and in none of the others. */
  "destination.myWork": "My work",
  /** A group's own pages, each read inside the group named above them. */
  "destination.work": "Work",
  "destination.workflows": "Workflows",
  "destination.questions": "Questions",
  "destination.referenceLists": "Reference lists",
  "destination.members": "Members",

  /** The one group whose pages are drawn, picked from the reader's own by name or key. */
  "groupInForce.label": "Group",
  "groupInForce.noMatch": "None of your groups has a name or key holding that.",

  /**
   * The start page says that the reader arrived and nothing more. A word here
   * about where to go next would be a word about places some readers have none
   * of, which the navigation is careful not to tell them. Its heading is the
   * product's name, which is not a sentence and is held outside this catalogue.
   */
  "landing.detail": "You are signed in.",
  /** A screen that exists and has nothing on it yet, said in its own words. */
  "page.notBuilt": "Nothing is built here yet.",

  /** The estate's roles, in the words a reader is shown wherever one is named. */
  "estateRole.steward": "Steward",
  "estateRole.watcher": "Watcher",

  /** Everybody this system is used by, as against everybody in the directory. */
  "pool.label": "People in the pool",
  "pool.empty": "Nobody is in the pool.",
  "pool.noMatch": "Nobody in the pool matches that.",
  "pool.add": "Add somebody",

  /**
   * One person in the pool. The facts about them are headed alike in the list
   * and in the panel, so each is said once.
   */
  "person.heading": "Person",
  "person.userId": "User number",
  "person.name": "Name",
  "person.estateRoles": "Estate roles",
  "person.groups": "Groups",
  "person.who": "Who they are",
  /** Where the facts come from, said only because it is why none can be corrected here. */
  "person.whereHeld":
    "Taken from the directory when they were brought in; nothing here can change it.",
  "person.nameless": "No name is held for them.",
  "person.holds": "Held",
  "person.holdsNot": "Not held",
  "person.grant": "Grant {role}",
  "person.withdraw": "Withdraw {role}",
  "person.inNoGroup": "In no group.",
  /** Names nobody: a row a migration made was made by nobody here. */
  "person.seeded": "A migration put them in the pool. Nobody here did.",
  "person.remove": "Remove from the pool",
  "person.out": "{name} is out of the pool.",
  "person.in": "{name} is in the pool.",
  /** A change to somebody already in the pool, refused once the reader had moved on from them; each says in words what was not done. */
  "person.notTakenOut": "{name} is still in the pool: {refusal}",
  "person.rolesUnchanged": "{name}'s estate roles were not changed: {refusal}",
  "person.withdrawFirst":
    "{count, plural, one {Their estate role has to be withdrawn first: {roles}.} other {Their estate roles have to be withdrawn first: {roles}.}}",
  "person.leaveFirst":
    "{count, plural, one {They have to leave this group first: {groups}.} other {They have to leave these groups first: {groups}.}}",

  /** What finds somebody, in the pool and in the directory alike: the same words find them in both. */
  "person.numberOrName": "User number or name",

  /** Finding somebody in the directory, to bring into the pool. */
  "directory.noMatch": "Nobody in the directory matches that.",
  "directory.inPool": "Already in the pool.",
  "directory.bringIn": "Bring into the pool",
  "directory.pickFirst": "Pick somebody first.",
  "directory.abandon": "Cancel",
  "directory.underway":
    "They are being brought in, and that can no longer be called back.",

  /** Every group there is, as the estate keeps them: which there are, and never who is in one. */
  "register.label": "Groups in the register",
  "register.empty": "No group has been created yet.",
  "register.noMatch": "No group's name holds that.",
  "register.filter": "Part of a group's name",

  /**
   * One group, as the register shows it and as it is created. The key is what
   * everything cites it by; the name is only what it is called.
   */
  "group.heading": "Group",
  "group.key": "Key",
  "group.name": "Name",
  "group.canBeAdministered": "Can be administered",
  "group.members": "Members",
  /** Whether anybody in it may still change its membership, and never who. */
  "group.administrable": "Yes",
  "group.notAdministrable": "No",
  "group.create": "Create a group",
  /** Said beside the key before it is given, because afterwards there is no way to change it. */
  "group.keyHint":
    "What everything cites the group by. Held in capitals, and never changed.",
  "group.nameLimit":
    "A group's name is one to 128 characters on one line: no space but single plain ones between words, none at either end, and something in it that shows.",
  "group.keyLimit": "Two to sixteen English letters and nothing else.",
  /** The one role the estate ever sets in a group, and it sets it once. */
  "group.founder": "Who may change its membership",
  "group.pickFirst": "Pick who may change its membership first.",
  "group.make": "Create",
  "group.abandon": "Cancel",
  "group.underway":
    "It is being created, and that can no longer be called back.",
  "group.created": "{name} is in the register.",
  /** The one control on a row; the name tells one row's apart from the next. */
  "group.rename": "Rename",
  "group.renameOne": "Rename {name}",
  "group.renameTitle": "Rename a group",
  /** Said beside the key while renaming, which is where somebody might look for a way to change it. */
  "group.keyKept":
    "Everything cites the group by its key, so it is never changed.",
  "group.nameUnchanged": "Type a name other than the one it has.",
  "group.renameUnderway":
    "It is being renamed, and that can no longer be called back.",
  "group.renamed": "The group is called {name} now.",

  /** What every model has done, and apart from that what calls to each came to. */
  "measurements.models": "The models",
  "measurements.system": "This system",
  "measurements.model": "Model",
  "measurements.mode": "Mode",
  "measurements.productions": "Productions",
  "measurements.refusedOnReview": "Refused on review",
  "measurements.reviews": "Reviews",
  "measurements.refusing": "Refusing",
  "measurements.didNotFit": "Did not fit",
  "measurements.wentWrong": "Went wrong",
  "measurements.neverCameBack": "Never came back",
  "measurements.turnedAway": "Turned away",
  "measurements.nothingCalled": "No model has been called yet.",

  /** A group's roles, in the words a reader is shown wherever one is named. */
  "groupRole.operator": "Operator",
  "groupRole.overseer": "Overseer",
  "groupRole.owner": "Owner",

  /** Who is in one group and what each of them holds there, as the group itself keeps it. */
  "members.heading": "Members of {group}",
  "members.label": "Members of the group",
  "members.empty": "Nobody is in this group.",
  "members.noMatch": "No member of this group matches that.",
  "members.bringIn": "Bring somebody in",

  /** One member, as the panel beside the list shows them. */
  "member.heading": "Member",
  "member.roles": "Roles",
  "member.give": "Give {role}",
  "member.take": "Take {role} away",
  "member.remove": "Remove from the group",
  /** Said where a role giving is how they come back, nobody having to be searched for. */
  "member.noLonger":
    "No longer a member of this group. Giving a role here makes them one again.",
  /** Why a role is not offered for taking, and why they are not offered for removal. */
  "member.lastChanger":
    "Nobody else here may change this group's membership, so what lets them is not taken away.",
  "member.in": "{name} is in this group now.",
  "member.out": "{name} is no longer in this group.",
  /** A change to a member, refused once the reader had moved on from them; each says what was not done. */
  "member.notTakenOut": "{name} is still in this group: {refusal}",
  "member.rolesUnchanged": "{name}'s roles here were not changed: {refusal}",

  /** The one currency a group reads its costs in; once chosen, only ever changed. */
  "currency.label": "Currency",
  /** A currency the reader's language has a name for. */
  "currency.named": "{code} — {name}",
  "currency.noneChosen": "None chosen",
  "currency.read": "Currency: {currency}",
  "currency.notPriced": "No model is priced in it any longer.",
  "currency.chosen": "This group's costs are read in {currency} now.",

  /** A group's entries of one kind, one page per kind; each heading names the group. */
  "library.workflows": "Workflows of {group}",
  "library.questions": "Questions of {group}",
  "library.referenceLists": "Reference lists of {group}",
  "library.workflowsLabel": "The group's workflows",
  "library.questionsLabel": "The group's questions",
  "library.referenceListsLabel": "The group's reference lists",
  "library.noWorkflows": "This group has no workflows yet.",
  "library.noQuestions": "This group has no questions yet.",
  "library.noReferenceLists": "This group has no reference lists yet.",
  "library.startWorkflow": "Start a workflow",
  "library.startQuestion": "Start a question",
  "library.startReferenceList": "Start a reference list",
  "library.filter": "Part of a name",
  "library.noMatch": "No entry's name here holds that.",

  /** What kind of thing an entry is, wherever one is named. */
  "entryKind.workflow": "Workflow",
  "entryKind.question": "Question",
  "entryKind.reference_list": "Reference list",

  /** One entry, as its row and its own page show it. */
  "entry.name": "Name",
  "entry.purpose": "What it is for",
  "entry.kind": "Kind",
  "entry.inService": "In service",
  "entry.submitted": "Submitted",
  "entry.stopped": "Stopped",
  /** Which version is in service, or that none is. */
  "entry.inServiceVersion": "Version {number}",
  "entry.noneInService": "None",
  "entry.waiting": "Waiting",
  "entry.notWaiting": "No",
  "entry.isStopped": "Stopped",
  "entry.notStopped": "No",
  "entry.saysNothing": "It says nothing of what it is for.",
  /** Whether it is stopped from running, and where it is, who stopped it and when. */
  "entry.runs": "No. It may be run.",
  "entry.stoppedBy":
    "Yes, by {name}, {when}. Nothing runs it until it is let go.",
  "entry.stop": "Stop it being used",
  "entry.letGo": "Let it be used again",
  "entry.nameLimit":
    "A name is one to 128 characters on one line: no space but single plain ones between words, none at either end, and something in it that shows.",
  "entry.purposeLimit":
    "What it is for is at most 512 characters on one line, with something in it that shows.",
  "entry.purposeHint":
    "One line saying what it does, for whoever picks it. It may be left empty.",
  "entry.start": "Start",
  "entry.abandon": "Cancel",
  "entry.startUnderway":
    "It is being started, and that can no longer be called back.",
  "entry.rename": "Rename",
  "entry.renameTitle": "Rename this entry",
  "entry.renameUnderway":
    "It is being renamed, and that can no longer be called back.",
  "entry.unchanged": "Change the name or what it is for first.",

  /** The versions of one entry, newest first, and the one open. */
  "versions.label": "Versions",
  "versions.newDraft": "New draft",
  "version.number": "Version {number}",
  "version.draft": "Draft",
  "version.submitted": "Submitted",
  "version.in_service": "In service",
  "version.retired": "Retired",
  /** A version's row: its standing, who wrote it and, where it has one, who approved it. */
  "version.detail": "{standing} · {written}",
  "version.detailApproved": "{standing} · {written} · {approved}",
  "version.writtenBy": "Written by {names}",
  /** Names nobody: a version a migration wrote was written by nobody here. */
  "version.writtenByNobody": "A migration wrote it. Nobody here did.",
  "version.approvedBy": "Approved by {name}",
  /** Never said as though somebody had approved it. */
  "version.approvedByNobody":
    "A migration put it into service. Nobody approved it.",
  "version.pinCount":
    "{count, plural, =0 {Nothing in service pins it.} one {One version in service pins it.} other {# versions in service pin it.}}",
  "version.pinnedBy": "{name} ({kind}), version {number}",
  /** Said of a submitted version, which nobody may change and somebody else has to approve. */
  "version.waiting": "Waiting on anybody who may approve an entry here.",
  /** A submission or approval refused for pins retired since, each named beside what would replace it. */
  "pins.label": "Pinned, and retired since",
  "pins.replaceable":
    "{name} ({kind}), version {pinned}, is retired. Version {newest} is in service.",
  "pins.unreplaceable":
    "{name} ({kind}), version {pinned}, is retired. None of it is in service.",
  "pins.openNewest": "Open {name}, version {number}",
  "pins.onDraft":
    "Taking the version in service in place of each retired one is a change to this draft.",
  "pins.onSubmitted":
    "A submitted version cannot be changed: withdraw it first, then take the version in service in place of each retired one.",
  "version.acts": "What can be done",
  "version.submit": "Submit",
  "version.withdraw": "Withdraw",
  "version.approve": "Approve",
  "version.retire": "Retire",

  /** A step that could send a model more than it takes: said beside what does not hold, and refusing nothing. */
  "sendsPast.label": "What could be too long to send",
  "sendsPast.hint":
    "Worked out with every value at its limit, against what each model takes now, and only about. It is accepted and approved all the same; a run holds a step back only where what it would send is too long.",
  "sendsPast.producing":
    "{step}: what it could send {model} to produce runs about {past, plural, one {# unit} other {# units}} past what that model takes.",
  "sendsPast.reviewing":
    "{step}: what it could send {model} to review runs about {past, plural, one {# unit} other {# units}} past what that model takes.",
  /** {max} is the most a count arriving here keeps exactly; past it, only that it was passed is said. */
  "sendsPast.producingUncounted":
    "{step}: what it could send {model} to produce runs more than {max, plural, one {# unit} other {# units}} past what that model takes.",
  "sendsPast.reviewingUncounted":
    "{step}: what it could send {model} to review runs more than {max, plural, one {# unit} other {# units}} past what that model takes.",

  /** A submission refused for what the version holds, each place named where it is. */
  "contentProblems.label": "What does not hold yet",
  "contentProblems.at": "{part}: {problem}",
  "contentProblems.atField": "{part}, {field}: {problem}",
  "contentProblems.atTerm": "{part}, term {position}, {term}: {problem}",
  /** One level of the way down to a field, where its name alone would not say which. */
  "contentProblems.sameNamed": "{name} (field {position} there)",
  "contentPart.instruction": "The instruction",
  "contentPart.takes": "What it takes",
  "contentPart.gives": "The declared answer",
  /** What a workflow gives back, which is not an answer to anything. */
  "contentPart.workflowGives": "What it gives back",
  "contentPart.steps": "The steps",
  "contentPart.helper": "Whether a run may be helped",
  /** Where in the steps a problem is, each level said by what a reader reads it by. */
  "contentProblems.atStep": "{part}, {step}: {problem}",
  "contentProblems.atCase": "{part}, {step}, {case}: {problem}",
  "contentProblems.atInput": "{part}, {step}, input {field}: {problem}",
  "contentProblems.atCaseInput":
    "{part}, {step}, {case}, input {field}: {problem}",
  "contentProblems.atBinding": "{part}, {where}: {problem}",
  "contentProblems.caseOn": "the case on {term}",
  "contentProblems.fallback": "the fallback",
  "contentProblems.boundTo": "what fills {target}",
  "contentProblems.stepBoundTo": "{step}, what fills {target}",
  "contentProblems.caseBoundTo": "{step}, {case}, what fills {target}",
  "contentProblems.chosenBy": "what {step} chooses by",
  "contentPart.terms": "The terms",
  "contentPart.asking": "One asking of it",
  "contentProblem.instruction_missing":
    "It tells whoever answers it nothing yet.",
  "contentProblem.nothing_given_back":
    "It gives nothing back, so nothing downstream could name anything it made.",
  "contentProblem.name_repeated": "A field beside it already has this name.",
  "contentProblem.longest_missing":
    "A field of text says how long its value may be, and this one does not yet.",
  "contentProblem.list_missing":
    "A field of terms names the list they come from, and this one does not yet.",
  "contentProblem.most_missing":
    "A field holding many says how many it may hold, and this one does not yet.",
  "contentProblem.limit_past_largest":
    "At its limits, one value of it could be written out longer than one value may be.",
  /** {most} is the longest one value may be written out, the figure the server holds each value to. */
  "contentProblem.limitPastLargestOf":
    "At its limits, one value of it could be written out in more than {most, number} characters, the names and marks holding it together counted, the longest one value may be.",
  "contentProblem.no_fields_held":
    "A field holding fields declares at least one, and this one declares none yet.",
  "contentProblem.standing_missing":
    "A value given back says what it takes to stand, and this one does not yet.",
  "contentProblem.floor_missing":
    "A value standing above a confidence says above which, and this one does not yet.",
  "contentProblem.no_steps":
    "It holds no step, so it could give nothing back and act on nothing.",
  "contentProblem.step_name_repeated": "An earlier step already has this name.",
  "contentProblem.runs_missing": "It says nothing yet of what it runs.",
  "contentProblem.pin_elsewhere": "It pins a version this group does not hold.",
  "contentProblem.code_step_not_published":
    "The code step it names is not published to this group.",
  "contentProblem.code_step_not_declared":
    "This release declares nothing of what the code step it names takes and gives back.",
  "contentProblem.code_step_takes_and_gives_nothing":
    "The code step it names takes nothing and gives nothing back, so nothing it did could be seen.",
  "contentProblem.code_step_list_missing":
    "The code step it names takes a term from a version of a reference list that does not exist.",
  "contentProblem.code_step_list_not_yet_in_service":
    "The code step it names takes a term from a version of a reference list not yet in service.",
  "contentProblem.code_step_list_retired":
    "The code step it names takes a term from a version of a reference list since retired.",
  "contentProblem.producer_missing":
    "It says nothing yet of who produces its values.",
  "contentProblem.producer_not_held":
    "Its values are produced by a model this deployment does not hold.",
  "contentProblem.producer_mode_not_offered":
    "Its values are produced in a mode its model does not offer.",
  "contentProblem.tries_missing":
    "It says nothing yet of how many tries it may make.",
  "contentProblem.reviewer_not_held":
    "What it produces is reviewed by a model this deployment does not hold.",
  "contentProblem.reviewer_mode_not_offered":
    "What it produces is reviewed in a mode its model does not offer.",
  "contentProblem.model_gives_nothing":
    "A model is asked by it and it gives nothing back, so nothing listens to the model.",
  "contentProblem.discriminator_missing":
    "Nothing is bound yet to choose its case by.",
  "contentProblem.discriminator_not_term":
    "What it chooses by is not one term of a list.",
  "contentProblem.no_cases": "It has no case on any term yet.",
  "contentProblem.case_target_missing":
    "It leads to no workflow at a fixed version yet.",
  "contentProblem.case_not_offered":
    "Its term is not one the list it chooses by offers.",
  "contentProblem.case_repeated": "An earlier case is on the same term.",
  "contentProblem.case_gives_otherwise":
    "The workflow it leads to gives back other than what the route declares.",
  "contentProblem.input_unbound": "Nothing fills it yet.",
  "contentProblem.target_unknown":
    "It fills an input that what it binds into never declared.",
  "contentProblem.target_bound_twice":
    "An earlier binding already fills this input, or part of it.",
  "contentProblem.pointer_into_many":
    "It points through a field holding many, which names no place among them.",
  "contentProblem.source_unknown":
    "It points at nothing what it reads from declares.",
  "contentProblem.source_not_earlier":
    "It reads a step that does not come before the one it fills.",
  "contentProblem.source_does_not_fit":
    "What it reads does not fit what it fills.",
  "contentProblem.source_may_be_empty":
    "What it fills must be given, and what it reads need not be, so that may be empty.",
  "contentProblem.constant_does_not_fit":
    "The constant does not fit what it fills.",
  "contentProblem.constant_too_long":
    "The constant holds more than 8192 characters of text.",
  "contentProblem.constantTooLongBy":
    "The constant holds {excess, plural, one {one character} other {# characters}} of text more than the 8192 it may hold.",
  "contentProblem.constant_conceals":
    "The constant holds a character that shows nothing yet changes how text reads.",
  "contentProblem.output_unbound": "Nothing fills it yet.",
  "contentProblem.output_not_from_step":
    "What it gives back is filled from a step, and this is filled from elsewhere.",
  "contentProblem.helper_missing":
    "Runs may be helped, and no model is named to help them.",
  "contentProblem.helper_not_held":
    "Runs are helped by a model this deployment does not hold.",
  "contentProblem.helper_mode_not_offered":
    "Runs are helped in a mode their model does not offer.",
  "contentProblem.no_terms":
    "It holds no term yet, so nothing could answer with one.",
  "contentProblem.term_repeated":
    "A term before it is already this one, whatever the case either is written in.",
  /** {most} is the most one asking may send, the figure the server holds it to. */
  "contentProblem.asking_past_largest":
    "It could send {excess, plural, one {# character} other {# characters}} more than {most, number}, the most one asking may send.",
  /** {max} is the most a count arriving here keeps exactly; past it, only that it was passed is said. */
  "contentProblem.asking_past_largest_uncounted":
    "It could send more than {max, plural, one {# character} other {# characters}} past {most, number}, the most one asking may send.",
  /** The same, of a model reviewing what the step's question produced. */
  "contentProblem.reviewPastLargest":
    "A model reviewing what it produces could be sent {excess, plural, one {# character} other {# characters}} more than {most, number}, the most one asking may send.",
  "contentProblem.reviewPastLargestUncounted":
    "A model reviewing what it produces could be sent more than {max, plural, one {# character} other {# characters}} past {most, number}, the most one asking may send.",
  "contentProblem.takes_past_largest":
    "All it takes, together at their limits, could be written out longer than one value may be, and a run keeps what it was started with as one.",
  /** {most} is the longest one value may be written out, the figure the server holds all a workflow takes to. */
  "contentProblem.takesPastLargestOf":
    "All it takes, together at their limits, could be written out in more than {most, number} characters, the longest one value may be, and a run keeps what it was started with as one.",
  /** Said at the step: a model reviewing what the step's code step gives back; {most} as for asking_past_largest. */
  "contentProblem.code_step_review_past_largest":
    "A model reviewing what its code step gives back could be sent {excess, plural, one {# character} other {# characters}} more than {most, number}, the most one asking may send.",
  "contentProblem.codeStepReviewPastLargestUncounted":
    "A model reviewing what its code step gives back could be sent more than {max, plural, one {# character} other {# characters}} past {most, number}, the most one asking may send.",
  /** A problem this build has no words for, still named where it is. */
  "contentProblem.unknown": "Something here does not hold.",

  /** A question's content: what it tells whoever answers it, what it takes, and what it gives back. */
  "question.instruction": "The instruction",
  "question.instructionHint":
    "What whoever answers it is told to do. What it takes is given beside this, never inside it.",
  "question.saysNothing": "It tells nobody anything yet.",
  "question.saveInstruction": "Save the instruction",
  "question.instructionUnchanged": "Change the instruction first.",
  "question.takes": "What it takes",
  "question.saveTakes": "Save what it takes",
  "question.gives": "The declared answer",
  "question.saveGives": "Save the declared answer",
  "question.underway":
    "It is being saved, and that can no longer be called back.",
  "question.added": "What is added when it runs",
  "question.addedHint":
    "What a model is asked for on top of the instruction, in the shape the declared answer gives. Nobody edits it; a person answering fills the declared answer instead.",
  "question.addedNotYet":
    "It is shown once every field of the declared answer says all it has to.",
  /** A workflow's content: its halves, its steps and what fills them, what a run may spend and who may help. */
  "workflow.takes": "What it takes",
  "workflow.saveTakes": "Save what it takes",
  "workflow.gives": "What it gives back",
  "workflow.saveGives": "Save what it gives back",
  "workflow.underway":
    "It is being saved, and that can no longer be called back.",
  "workflow.writtenSince":
    "Somebody saved this draft since it was read here. What was typed here is kept; reading it afresh shows theirs in its place.",
  "workflow.readAfresh": "Read it afresh",
  "workflow.steps": "The steps",
  "workflow.stepsNone": "No step yet.",
  "workflow.addStep": "Add a step",
  "workflow.saveSteps": "Save the steps and what fills what it gives back",
  "workflow.heldAt": "{step}: {why}",
  "workflow.stepsUnchanged":
    "Change a step or what fills what it gives back first.",
  "workflow.order": "Order",
  "workflow.name": "Name",
  "workflow.runs": "Runs",
  "workflow.produces": "Produces",
  "workflow.reviewedBy": "Reviewed by",
  "workflow.givesBack": "Gives back",
  "workflow.unnamed": "Step {position}, not named yet",
  "workflow.open": "Open {name}",
  "workflow.up": "Move {name} up",
  "workflow.down": "Move {name} down",
  "workflow.remove": "Take {name} out",
  "workflow.runsNothing": "Nothing chosen yet",
  "workflow.runsVersion": "{name}, version {number}",
  "workflow.runsCode": "Code step {name}",
  "workflow.runsRoute": "A route",
  "workflow.newerInService":
    "Version {number} of what it runs is in service and newer.",
  "workflow.pinRetired":
    "The version pinned is retired. It is kept while this is a draft, and submitting refuses it.",
  "workflow.takeNewer": "Take version {number}",
  "workflow.takeNewerFor": "Take version {number} for {name}",
  "workflow.producesPerson": "A person",
  "workflow.producesCode": "Code",
  "workflow.producesPersonDone": "A person saying it was done",
  "workflow.producesNobody": "Nobody",
  "workflow.producesUnchosen": "Not chosen yet",
  "workflow.modelAsItIs": "{model}",
  "workflow.modelInMode": "{model} in {mode}",
  "workflow.givesCount":
    "{count, plural, =0 {Nothing} one {One value} other {# values}}",
  "workflow.givesUnknown": "Not known here",
  "workflow.stepName": "Name",
  "workflow.stepRuns": "Runs",
  "workflow.runsChoose": "Nothing yet",
  "workflow.runsQuestion": "A question",
  "workflow.runsWorkflow": "A workflow",
  "workflow.runsCodeStep": "A code step",
  "workflow.runsRouteOption": "A route",
  "workflow.version": "Version",
  "workflow.versionNone": "None chosen yet",
  "workflow.codeStep": "Code step",
  "workflow.codeStepNone": "None chosen yet",
  "workflow.codeStepUndeclared":
    "What this code step takes is not offered to this group, so there is nothing to fill here.",
  "workflow.producer": "Who produces its values",
  "workflow.producerNone": "Not chosen yet",
  "workflow.producerPerson": "A person",
  "workflow.producerModel": "A model",
  "workflow.producerCode": "Code",
  "workflow.producerPersonDone": "A person, saying it was done",
  "workflow.model": "Model",
  "workflow.modelNone": "None chosen yet",
  "workflow.mode": "Mode",
  "workflow.modeAsItIs": "As it is",
  "workflow.told": "A model asked again is told what happened",
  "workflow.tries": "How many tries",
  "workflow.triesLimit": "Tries are a whole number from 1.",
  "workflow.reviewer": "Who may review",
  "workflow.reviewerPerson": "A person",
  "workflow.reviewerModel": "A model",
  "workflow.reviewerUnchosen":
    "A model is to review what it produces, and none is chosen yet.",
  "workflow.reviewerOnlyModel":
    "This deployment holds one model, so a model reviewing is the one that produces.",
  "workflow.inputs": "What fills each input",
  "workflow.inputsNone": "It takes nothing, so nothing is bound.",
  "workflow.inputsUnknown":
    "What it takes is not known here, so nothing is offered to fill.",
  "workflow.from": "From",
  "workflow.fromNothing": "Nothing yet",
  "workflow.fromInput": "What the workflow takes",
  "workflow.fromStep": "Step {position}: {name}",
  "workflow.fromConstant": "A constant",
  "workflow.pointer": "Which",
  "workflow.pointerNone": "None chosen yet",
  "workflow.constant": "The constant",
  "workflow.constantNumber": "The number",
  "workflow.constantWritten":
    "The constant, written out: text in double quotes, many in square brackets, fields in braces",
  "workflow.yes": "Yes",
  "workflow.no": "No",
  "workflow.constantSaid": "A constant: {typed}",
  "workflow.readAt": "{place}, {path}",
  "workflow.constantUnreadable":
    "What is typed is no value written out: text in double quotes, many in square brackets, fields in braces.",
  "workflow.numberUnreadable":
    "A number is written in digits, with a point before any fraction, and nothing else; a zero is never written with a minus sign.",
  /** Each figure is the rule's own, passed as written: {digits}, {firstYear}, {lastYear}, {fraction}, {furthest}. */
  "workflow.numberPastDigits":
    "A number is written in at most {digits} digits in all, before and after its point together.",
  "workflow.dateUnreadable":
    "A date is written year-month-day, such as 2024-03-31, the year from {firstYear} to {lastYear}.",
  "workflow.momentUnreadable":
    "A moment is written as a date, T, a time to the second with at most {fraction} digits of its fraction, and its offset as a sign, hours and minutes no further than {furthest} either way, such as 2024-03-31T09:30:00.5+02:00; never Z or -00:00.",
  "workflow.pointsForward":
    "It reads a step that does not come before this one, which submitting refuses.",
  "workflow.sourceItself": "A step never reads what it gives back itself.",
  "workflow.nothingFits": "Nothing there fits this.",
  "workflow.chosenBy": "What it chooses by",
  "workflow.routeGives": "What every case gives back",
  "workflow.cases": "Cases",
  "workflow.casesNone": "No case yet.",
  "workflow.addCase": "Add a case",
  "workflow.removeCase": "Take this case out",
  "workflow.removeCaseCalled": "Take out {name}",
  "workflow.term": "Term",
  "workflow.termNone": "None chosen yet",
  "workflow.termLimit":
    "A term is one to 128 characters on one line, as a list holds it.",
  "workflow.fallback": "The fallback, taking what no case claims",
  "workflow.fallbackSaid": "The fallback",
  "workflow.caseSaid": "On {term}",
  "workflow.caseOnNothing": "A case on no term yet",
  "workflow.caseWorkflow": "Leads to",
  "workflow.caseInputs": "What fills each input of what it leads to",
  "workflow.outputs": "What fills each value it gives back",
  "workflow.outputsNone": "It gives nothing back, so nothing is filled.",
  "workflow.outputUnbound": "Nothing fills it yet, which submitting refuses.",
  "workflow.ceilingPart": "What a run may spend",
  "workflow.ceiling": "Ceiling",
  "workflow.ceilingHint":
    "What is sent and what comes back, added together. Leave it empty for no ceiling.",
  "workflow.ceilingNone": "Runs of it have no ceiling.",
  "workflow.ceilingSaid":
    "Runs of it may spend at most {ceiling}, what is sent and what comes back added together.",
  "workflow.keepsOwn": "A run beneath another is held to this ceiling as well",
  "workflow.raiseNeedsApproval":
    "Raising or taking away a run's ceiling waits on somebody who may approve an entry",
  "workflow.saveCeiling": "Save what a run may spend",
  "workflow.helpPart": "Whether a run may be helped",
  "workflow.mayBeHelped": "Runs may be helped",
  "workflow.saveHelp": "Save whether a run may be helped",
  "workflow.notHelped": "Runs may not be helped.",
  "workflow.helpedBy": "Runs may be helped, by {model}.",
  "workflow.helperUnchosen": "Runs may be helped, by a model not chosen yet.",
  "workflow.unchanged": "Change something first.",
  "workflow.problemsHere": "What does not hold here yet",
  "added.confidence": "Asked how sure it is.",
  "added.note": "On choosing among them: {note}",
  "added.term": "{term}: {meaning}",

  /** A reference list's content: a note on choosing among its terms, and the terms, each with what it means. */
  "referenceList.note": "The note",
  "referenceList.noteHint":
    "How to go about choosing among the terms at all. What is true of one term goes in what it means.",
  "referenceList.saysNothing": "It says nothing on choosing among its terms.",
  "referenceList.saveNote": "Save the note",
  "referenceList.noteUnchanged": "Change the note first.",
  "referenceList.terms": "The terms",
  "referenceList.term": "Term",
  "referenceList.meaning": "What it means",
  /** Heads the column of what can be done to each term, where the reader may change them. */
  "referenceList.changes": "Changes",
  "referenceList.noTerms": "It holds no term yet.",
  "referenceList.termAt": "Term {position}",
  "referenceList.meaningAt": "What term {position} means",
  "referenceList.newTerm": "New term",
  "referenceList.newMeaning": "What the new term means",
  "referenceList.add": "Add the term",
  "referenceList.addFirst": "Write a term and what it means first.",
  "referenceList.full":
    "A reference list holds at most {most} terms. Remove one to add another.",
  "referenceList.save": "Save",
  "referenceList.up": "Move up",
  "referenceList.down": "Move down",
  "referenceList.remove": "Remove",
  /** One control on a term's row, named with the term, since every row has one alike. */
  "referenceList.onTerm": "{act}: {term}",
  "referenceList.alike":
    "Alike to a term above it, whatever the case either is written in. Submitting refuses it.",
  /** Said once a change to the terms has landed, each naming the term it was made to. */
  "referenceList.added": "{term} is added as the last term.",
  "referenceList.saved": "{term} is saved.",
  "referenceList.moved": "{term} is moved to place {position}.",
  "referenceList.removed": "{term} is removed.",
  "referenceList.underway":
    "It is being saved, and that can no longer be called back.",

  /** A write refused for the draft having been written since the page read it. */
  "draft.readAfresh": "Reload",
  "draft.readAfreshHint":
    "What is typed here is kept until you reload. Reloading shows the draft as it is saved now, and drops whatever here was not saved.",

  /** One half of a declaration, a field at a time, as a builder draws and edits it. */
  "declaration.none": "Nothing is declared.",
  "declaration.add": "Add a field",
  "declaration.addInside": "Add a field inside {name}",
  "declaration.remove": "Remove {name}",
  "declaration.up": "Move {name} up",
  "declaration.down": "Move {name} down",
  "declaration.unchanged": "Change something first.",
  "declaration.unnamed": "Field {position}, not named yet",
  "declaration.held": "This field keeps the half from being saved: {why}",
  "declaration.name": "Name",
  "declaration.label": "Label",
  "declaration.labelLimit":
    "A label is at most 128 characters on one line, with something in it that shows.",
  "declaration.help": "Help",
  "declaration.helpLimit":
    "Help is at most 512 characters on one line, with something in it that shows.",
  "declaration.kind": "What it is",
  "declaration.longest": "How long, in characters",
  "declaration.many": "Holds many",
  "declaration.most": "At most",
  "declaration.limit": "A limit is a whole number from 1 to 2147483647.",
  "declaration.kindDropsFields":
    "Changing what it is leaves out the fields it holds; they are sent again only if it holds fields once more.",
  "declaration.list": "From",
  "declaration.listNone": "None chosen yet",
  "declaration.listVersion": "{name}, version {number}",
  "declaration.listNewer":
    "Version {number} of this list is in service and newer.",
  "declaration.listRetired":
    "The version pinned is retired. It is kept while this is a draft, and submitting refuses it.",
  "declaration.listRetiredNewest":
    "The version pinned is retired, and version {number} is in service. It is kept while this is a draft, and submitting refuses it.",
  "declaration.mustBeGiven": "Must be given",
  "declaration.stands": "What it takes to stand",
  "declaration.standsNone": "None chosen yet",
  "declaration.floor": "Above, in percent",
  "declaration.floorLimit": "A confidence is a whole number from 1 to 100.",
  "declaration.one": "Holds one",
  "declaration.manyUpTo": "Holds many, at most {most}",
  "declaration.manyUnsaid": "Holds many, how many not said yet",
  "declaration.longestSaid": "At most {longest} characters",
  "declaration.longestUnsaid": "How long not said yet",
  "declaration.fromSaid": "From {name}, version {number}",
  "declaration.fromUnsaid": "No list chosen yet",
  "declaration.given": "Must be given",
  "declaration.mayBeEmpty": "May be left empty",
  "declaration.standsAbove": "Stands above {floor} percent",
  "declaration.standsAboveUnsaid": "Stands above a confidence not said yet",
  "declaration.standsUnsaid": "What it takes to stand not said yet",
  "fieldKind.text": "Text",
  "fieldKind.number": "A number",
  "fieldKind.date": "A date",
  "fieldKind.moment": "A moment",
  "fieldKind.yes_no": "Yes or no",
  "fieldKind.term": "A term",
  "fieldKind.fields": "Fields of its own",
  "fieldStanding.always": "Always stands; nobody is asked",
  "fieldStanding.never": "Somebody is always asked",
  "fieldStanding.above_confidence": "Stands above a stated confidence",

  /** Finding somebody in the pool to bring into a group; whoever is in it already is not offered. */
  "candidates.noMatch": "Nobody in the pool outside this group matches that.",
  "candidates.roles": "Roles here",
  "candidates.pickFirst": "Pick somebody first.",
  "candidates.pickRole":
    "Pick at least one role: somebody holding nothing here is not a member.",
  "candidates.takeOn": "Take them on",
  "candidates.abandon": "Cancel",
  "candidates.underway":
    "They are being taken on, and that can no longer be called back.",

  /** One run, on the page it is watched on. */
  "run.title": "Run {number}",
  "run.number": "Number",
  "run.workflow": "Workflow",
  "run.workflowVersion": "{name}, version {version}",
  "run.started": "Started",
  "run.startedBy": "By {name}, {when}",
  "run.startedAbove": "By the run above it, {when}",
  "run.above": "Beneath",
  "run.openAbove": "The run above it",
  "run.where": "Where it is",
  "run.stoppedBy": "Stopped by {name}, {when}",
  /** A ceiling reached names nobody as having stopped the run. */
  "run.stoppedByOwnCeiling": "Stopped by its ceiling, {when}",
  "run.stoppedByCeilingOf": "Stopped by the ceiling of run {number}, {when}",
  /** Where a run is, by the state the server works out. */
  "runState.running": "Running",
  "runState.runningAt": "Running, on {step}",
  "runState.stopped": "Stopped",
  "runState.failed": "Failed",
  "runState.done": "Done",
  "runState.unknown": "Not something this page can say yet.",
  "run.stop": "Stop",
  "run.openAgain": "Open again",
  "run.rename": "Rename",
  "run.cost": "What it has cost",
  "run.spent": "{spent} in all: {sent} sent, {cameBack} came back",
  /** Who counted it, where a model did not, of any figure: a try's may add up a call to produce and one to review. */
  "run.someMeasuredHere":
    "Some or all of it is as this system measured it, where a model did not say what it counted.",
  "run.cameBackUnknown":
    "What came back is not known for every call yet, and is counted here as nothing.",
  "run.ceiling": "Ceiling",
  "run.noCeiling": "None. It may spend without limit.",
  "run.heldBy": "Held to the ceiling of run {number}, at the top",
  "run.changeCeiling": "Change the ceiling",
  "run.abandon": "Cancel",
  /** A run in detail under its header, and one step of it on a page of its own. */
  "step.startedWith": "What it was started with",
  "step.startedWithNothing":
    "Its workflow takes nothing, so it was started with nothing.",
  "step.startedAboveWith": "The run above it started it, with {workflow}.",
  "step.gaveBack": "What it gave back",
  "step.givesNothing":
    "Its workflow gives nothing back: it acts rather than answers.",
  "step.nothingStandsYet": "Nothing it gives back stands yet.",
  "step.theSteps": "The steps",
  "step.order": "Order",
  "step.name": "Name",
  "step.takesFrom": "Takes from",
  "step.cost": "Cost",
  "step.takesNothing": "It takes nothing.",
  "step.takes": "{input}: {from}",
  "step.fromRunInput": "{field}, which the run was started with",
  "step.fromStep": "{field}, which {step} gave back",
  "step.fromConstant": "a value written into the workflow",
  "step.notStarted": "Not started",
  "step.running": "Running",
  "step.heldBack": "Held back",
  "step.waiting": "Waiting",
  "step.failed": "Failed",
  "step.done": "Done",
  "step.unknown": "Not something this page can say yet.",
  "step.heldEntryStopped":
    "What it runs was stopped, so nothing is produced until that is undone.",
  "step.heldStopLetGo":
    "What stopped it has been let go, so it goes on by itself while the run runs.",
  "step.heldWorkflowStopped":
    "The workflow this run runs was stopped, so nothing is produced until that is undone.",
  "step.heldCodeStepNotHeld":
    "This system, as it runs now, does not include the code this step runs, so the step waits, and goes on once the system includes that code again. Later runs can use a new version of the workflow.",
  "step.heldTooLong":
    "What it would send is longer than the model it names takes, so it was not sent, and nothing was spent on it.",
  "step.heldTurnedAway": "The model it names would not take it.",
  "step.heldSpentUp":
    "The model it names would not take it, as what may be spent with that model is used up, so it is not sent again by itself.",
  "step.stoppedBy": "Stopped by {name}, {when}.",
  "step.stoppedByGone":
    "Stopped {when}, by somebody who can no longer be found.",
  "step.notReviewedYetOf": "{field} is not reviewed yet.",
  "step.owedAsked": "Try {number} has been asked for.",
  "step.owedUnasked": "Try {number} is not asked for yet.",
  "step.failedTriesSpent":
    "Every try it allows has been made, and none of them stands.",
  "step.failedUncuttable":
    "What cannot be cut from what it would send is already longer than the model it names takes, so no cutting could mend it.",
  "step.failedModelNotHeld":
    "It names a model this deployment does not hold, or a mode that model does not offer.",
  /** {model} is the model named, in its mode where it runs in one. */
  "step.failedProducerNotHeld":
    "It names {model} to produce it, which this deployment does not offer.",
  "step.failedReviewerNotHeld":
    "It names {model} to review it, which this deployment does not offer.",
  "step.runningCode": "Its code is running.",
  "step.runningCall": "A call to the model it names is out.",
  "step.runningNextTry":
    "A try of it is made by this system, by itself, while the run runs.",
  "step.waitsOnReviewer": "It waits on somebody who may review it.",
  "step.waitsOnModel": "It waits on a model's review.",
  "step.waitsOnAnswerer": "It waits on somebody who may answer it.",
  "step.waitsOnStarter": "It waits on whoever started the run.",
  "step.waitsOnNobody": "It waits on nobody while the run is stopped.",
  /** Who can deal with a step held back or failed, which never waits on anybody. */
  "step.trySendingBy": "Somebody who may start a run can try sending it.",
  "step.letGo": "Somebody who may revoke an entry can let what was stopped go.",
  "step.letGoThenTrySending":
    "Somebody who may revoke an entry can let what was stopped go, and then somebody who may start a run can try sending it.",
  "step.nobodyWhileStopped": "Nobody can act on it while the run is stopped.",
  /** Said once, where a re-read finds a run or a step in another state; {state} is a run's or a step's state as drawn. */
  "step.nowIn": "{name}: now {state}.",
  "step.nowUnknown": "{name}: now somewhere this page cannot say yet.",
  "step.noCost": "Nothing: it calls no model.",
  "step.aPerson": "A person",
  "step.code": "Code",
  "step.back": "Back to the run",
  "step.orderOf": "{order} of {of}",
  "step.runs": "What it runs",
  "step.runsCode": "Code: {name}",
  "step.runsRoute": "A route to the steps after it",
  "step.producedBy": "Produced by",
  "step.producesNothing": "Nothing: it produces nothing of its own.",
  "step.reviewedBy": "Reviewed by",
  "step.reviewerPerson": "Somebody who may review it",
  "step.nobodyReviews": "Nobody reviews it.",
  "step.tries": "Tries",
  "step.tryNumber": "Try {number}",
  "step.tryOf": "Try {number} of the {allowed} it allows",
  "step.tryBeyond": "Try {number}, past the {allowed} it allows",
  "step.wentIn": "What went in",
  "step.nothingYet": "Nothing yet.",
  "step.notYetSent": "Nothing is sent yet: this is what it would take now.",
  "step.cameOut": "What came out",
  "step.producedNothing": "It has produced nothing yet.",
  "step.stands": "It stands.",
  "step.waitsOnReview": "It waits on review.",
  "step.refusedOnReview": "Refused on review.",
  "step.refusedForLength": "Refused for its length.",
  "step.nowNone": "Its newest try gave nothing back for it.",
  "step.seeTries": "See the tries of {field}",
  "step.theTries": "The tries",
  "step.triesOfValue": "The tries of {field}",
  "step.noTries": "No try has been made yet.",
  "step.try": "Try",
  "step.howItEnded": "How it ended",
  "step.endedOpen": "Nothing has come back yet.",
  "step.didNotFit": "What came back did not fit what was declared.",
  "step.errored": "It went wrong.",
  "step.nothingCameBack": "Nothing came back.",
  /** Which way a model's answer, or a model's review, did not fit, as it was worked out when it arrived. */
  "step.misfitNotTheShape":
    "The answer could not be read as what it was asked for.",
  "step.misfitFieldMissing": "The answer left out a value it was asked for.",
  "step.misfitFieldUnknown": "The answer gave a value nothing asked for.",
  "step.misfitNothingGiven":
    "The answer gave nothing for a value that must be given.",
  "step.misfitNotItsKind":
    "The answer gave a value of the wrong kind for its field.",
  "step.misfitTooLong": "The answer gave a value longer than its field allows.",
  "step.misfitTooMany":
    "The answer gave more of a value than its field allows.",
  "step.misfitNotATerm":
    "The answer gave a value that is none of its field's terms.",
  "step.misfitUnkeepable":
    "The answer gave text holding a character that cannot be kept.",
  "step.misfitTooLongToKeep":
    "The answer gave a value that fits its field but is longer than any one value may be kept.",
  "step.misfitConfidenceMissing":
    "The answer did not say how sure it was of a value it was asked to.",
  "step.misfitConfidenceUnasked":
    "The answer said how sure it was of a value nobody asked that of.",
  "step.misfitConfidenceNotAPercent":
    "The answer said how sure it was as something other than a whole number from 0 to 100.",
  "step.misfitUndecided":
    "The review left a value neither assured nor refused.",
  "step.misfitWordsMissing": "The review refused a value without saying why.",
  "step.misfitWordsTooLong":
    "The review's words for a refusal were longer than such words may be.",
  "step.misfitWordsUnkeepable":
    "The review's words for a refusal held a character such words may not hold.",
  "step.misfitCutOff":
    "The model stopped at the most it may give back, so its answer was cut short.",
  "step.misfitNotKeptAsItCame":
    "The answer held something that could not be kept exactly as it came.",
  /** Each time a model turned a call away: none of them is a try, and none cost anything. */
  "step.turnedAway": "Times the model would not take it",
  "step.turnedAwayAt": "Turned away {when}.",
  "step.turnedAwaySentAgain": "Turned away {when}, and sent again by itself.",
  "step.turnedAwaySaid": "The model said: {said}",
  "step.turnedAwaySaidCut": "The model said: {said} (cut short here)",
  "step.turnedAwayWithheld": "What the model said is withheld from you.",
  "step.turnedAwayCostNothing":
    "None of these is a try, and none of them cost anything.",
  "step.notReviewedYet": "Nobody has reviewed it yet.",
  "step.noReviewAsked": "Nobody was asked to review it.",
  "step.reviewWentWrong": "{who}, whose review went wrong",
  "step.askedBy": "Asked for by",
  "step.askedByRun": "The run itself",
  "step.why": "Why, in their words",
  "step.gaveNothingFor": "It gave nothing back for this.",
  "step.decision": "What the review said",
  "step.assured": "Assured.",
  "step.refused": "Refused.",
  "step.refusedWith": "Refused: {why}",
  "step.whyWithheld": "Refused, in words withheld from you.",
  "step.wentWrong": "What went wrong",
  "step.wentWrongCut": "{detail} (cut short here)",
  "step.returned": "What its code gave back",
  "step.howSure": "How sure",
  /** {percent} is written as the reader writes a percentage. */
  "step.sureOf": "{field}: {percent}",
  /** A field within the field holding it, the outermost first. */
  "step.fieldWithin": "{outer} › {inner}",
  /** One of many a field holds, counted from one. */
  "step.itemOf": "{field}, item {number}",
  /** A value as it was filled. */
  "step.none": "None",
  "step.withheld": "Withheld from you.",
  "step.unreadable": "Written in a way this page cannot read.",
  /** Said beside a value kept in a shape its field no longer has, or of a field no longer declared. */
  "step.earlierShape":
    "Given in the shape this step had before; shown as it was kept.",
  "step.term": "{term}: {meaning}",
  /** {offset} is the one it was given in, written as +02:00 is. */
  "step.momentOwn": "{when}, UTC{offset}",
  "step.momentLocal": "{when} on your own clock",
  /** A run drawn as a conversation: one message for what it was started with, one per step reached, and how it ended. */
  "step.progress": "{done} of {of, plural, one {# step} other {# steps}} done",
  "step.more": "More",
  "step.showInDetail": "Show in detail",
  "step.theConversation": "The conversation",
  "step.startedByOn":
    "{name} started it, {when}, with {workflow}, version {version}.",
  "step.startedAboveOn":
    "The run above it started it, {when}, with {workflow}, version {version}.",
  "step.inFull": "{field}, in full",
  "step.since": "Since {when}",
  "step.details": "Details",
  "step.earlierTry": "Earlier try",
  "step.laterTry": "Later try",
  "step.openStep": "Open this step's page",
  "step.comesNext": "Not reached yet: {steps}",
  "step.stoodByThen": "What stood by then",
  "step.failedAt": "It failed at {step}.",
  /** Why an act is not offered to the reader, where the reason is theirs rather than the step's. */
  "step.mayNotAnswer": "You may not answer it here.",
  "step.mayNotAskAgain": "You may not ask for it again.",
  "step.mayNotReview": "You may not review it.",
  "step.mayNotTrySending": "You may not try sending it.",
  "step.reviewsOwn": "You gave this, so somebody else reviews it.",
  /** One review deciding every value waiting on the reader, each assured or refused with a reason. */
  "step.yourReview": "Your review",
  "step.assure": "Assure",
  "step.refuse": "Refuse",
  "step.whyRefuse": "Why you refuse {field}",
  "step.submitReview": "Submit this review",
  "step.chooseEach":
    "Choose Assure or Refuse for each value, and say why for each one refused.",
  "step.sayWhy": "Say why you refuse it.",
  "step.reviewedAlready": "This was reviewed already, by {name}.",
  /** The next try of a step: asked of whoever it names, or answered here by the reader. */
  "step.askAgain": "Ask again",
  "step.answerHere": "Answer it here",
  /** A model's try that could not be sent, sent to it; the press is answered before anything is sent. */
  "step.trySending": "Try sending",
  "step.trySendingOut": "Asking for it to be sent.",
  "step.trySendingSent":
    "It will be sent if it can be. What comes of it shows here once it is known.",
  "step.nextBeyond":
    "Try {number} goes past the {allowed, plural, one {# try} other {# tries}} its step allows.",
  "step.theInstruction": "What it asks",
  "step.yourAnswer": "Your answer",
  "step.startsFromTry":
    "It starts from what try {number} gave, and every value is given again.",
  "step.lastWithheld": "What try {number} gave here is withheld from you.",
  "step.lastEarlierShape":
    "What try {number} gave here was in the shape this step had before, so it starts empty.",
  "step.whyAnswer": "Why you are answering this way",
  "step.send": "Send this answer",
  "step.askedAlready": "Asked for already, by {name}.",
  "step.answeredAlready": "Answered already, by {name}.",

  /** What a group has running, on one page drawn two ways; the reader picks the way, and this device keeps it. */
  "work.heading": "Work of {group}",
  "work.drawn": "How this page is drawn",
  "work.asConversation": "As a conversation",
  "work.inDetail": "In detail",
  "work.newRun": "New run",
  "work.filter": "Part of a run's name, or its workflow's",
  "work.theRuns": "The runs",
  "work.today": "Today",
  "work.yesterday": "Yesterday",
  "work.earlier": "Earlier",
  "work.line": "{workflow} · {where}",
  "work.aNewRun": "A new run",
  "work.nothingOffered":
    "No workflow of this group can be started: none has a version in service that is not stopped.",
  "work.openOne": "Open a run from the list to read it here.",
  "work.whatIsRunning": "What is running",
  "work.run": "Run",
  "work.runKey": "{key}-{number}",
  "work.name": "Name",
  "work.startedBy": "Started by",
  "work.noRuns": "Nothing has been run here yet.",
  "work.noneReadable":
    "Reading a run is a permission this group has not given you, so no run is listed, including the ones you started.",
  "work.noMatch":
    "No run here, or its workflow, is called anything holding that.",
  "work.noOwnRuns": "You have started no run here yet.",
  "work.noOwnMatch": "No run you started matches that.",
  /** Starting a run: a name, the workflow and its version, and what that version takes. */
  "work.startARun": "Start a run",
  "work.start": "Start",
  "work.abandon": "Cancel",
  "work.startUnderway":
    "It is being started, and that can no longer be called back.",
  "work.nameThisRun": "Name of this run",
  /** A name suggested where nothing typed gives one; {time} is when the form was drawn, in the reader's own way. */
  "work.nameSuggested": "{workflow} {time}",
  "work.pickWorkflow": "Choose a workflow first.",
  "work.version": "Version",
  "work.versionNumbered": "Version {number}",
  "work.nothingTaken": "It takes nothing, so it may be started as it is.",
  "work.heldMissing": "A field that must be given is still empty.",
  "work.heldUnfit": "A value does not fit its field yet; each one says why.",
  /** {run} is the run's key and number. */
  "work.startedUnreadable":
    "{run} has begun. Reading it is a permission this group has not given you, so it cannot be opened here.",
  "work.noLongerOffered":
    "That version can no longer be started here, so what may be started has been read again.",
  /** Filling in what a workflow takes, one control to a field; each reason is one the server names a value by. */
  "fill.missing": "This must be given.",
  "fill.malformed": "This is not written as this field takes it.",
  "fill.too_long": "This is longer than this field takes.",
  "fill.too_many": "This holds more than this field takes.",
  "fill.not_a_term": "This is none of the terms this field offers.",
  "fill.crlf":
    "Lines here end in a line feed alone, never in a carriage return and a line feed (CRLF).",
  "fill.direction_control":
    "This holds a direction control, which text here may not hold.",
  "fill.tag":
    "This holds a tag character, which shows nothing and which text here may not hold.",
  "fill.unusable":
    "This holds a character text here may not hold: a control other than a tab or a line feed, a line or paragraph separator, or half of a pair.",
  "fill.moreProblems":
    "{count, plural, one {# more place does not fit and is not marked.} other {# more places do not fit and are not marked.}}",
  "fill.numberHow":
    "Written in digits, with a point before any fraction, such as 1234.5, in at most {digits} digits in all.",
  "fill.count": "{count} / at most {most}",
  "fill.none": "None yet.",
  "fill.addOne": "Add one to {label}",
  "fill.takeAway": "Take away",
  "fill.takeAwayOne": "Take away {element}",
  "fill.element": "{label} {position}",
  "fill.leaveEmpty": "Leave empty",
  "fill.yes": "Yes",
  "fill.no": "No",
  "fill.date": "Date",
  "fill.time": "Time",
  "fill.offset": "Offset",
  "fill.chooseVersion": "Choose another version",
  /** A raise asked for, which is not in force until it is approved. */
  "raise.to":
    "{name} asked, {when}, for it to be raised to {to}. That waits on approval.",
  "raise.away":
    "{name} asked, {when}, for it to be taken away. That waits on approval.",
  "raise.approve": "Approve the raise",
  "raise.refuse": "Refuse the raise",
  "raise.withdraw": "Withdraw the raise",
  /** Changing a run's ceiling, where nothing typed means none. */
  "ceiling.title": "Change the ceiling",
  "ceiling.label": "Ceiling",
  "ceiling.hint": "Left empty, the run has no ceiling.",
  "ceiling.limit":
    "A ceiling is a whole number from one to 9,007,199,254,740,991, written in digits.",
  "ceiling.unchanged": "That is the ceiling it has.",
  "ceiling.approval":
    "A raise, or taking the ceiling away, waits on approval; until then the run keeps the ceiling it has.",
  "ceiling.withdraws":
    "A raise waiting on it is withdrawn by any other change asked for here.",
  "ceiling.change": "Change",
  "ceiling.underway":
    "It is being changed, and that can no longer be called back.",
  /** Renaming a run, which two runs may share a name. */
  "runName.title": "Rename this run",
  "runName.label": "Name",
  "runName.limit":
    "A run's name is one to 128 characters on one line, with something in it that shows.",
  "runName.unchanged": "Change the name first.",
  "runName.underway":
    "It is being renamed, and that can no longer be called back.",

  /** An address that names nothing, which no amount of retrying will cure. */
  "routeError.missing": "No such screen",
  "routeError.missingDetail": "The address does not name anything here.",
  "routeError.missingWayBack": "Back to the start",
  /** A screen that broke while it was shown; what went wrong is never shown to the reader. */
  "routeError.broken": "Something went wrong on this page.",
  "routeError.brokenDetail":
    "Nothing you saved is lost. Go to another page from the menu, or reload this one.",
  "routeError.brokenReload": "Reload this page",
  /** The frame broke, and the menu with it, so nothing here points at one. */
  "routeError.frameBroken": "Something went wrong.",
  "routeError.frameBrokenDetail":
    "Nothing you saved is lost. Reload to carry on.",
  "routeError.frameBrokenReload": "Reload",

  /**
   * What this side has to say for itself, as against what a server said. None
   * of these is keyed by anything a server sends, which is
   * why they are kept out of the namespace below: an id there is a served code,
   * and a gateway answering `{"code":"stopped"}` would otherwise be telling the
   * reader that this screen cancelled their request.
   */
  "failure.stopped": "The request was stopped from this screen.",
  /** A fault in this side's own code, whose message is reported rather than shown. */
  "failure.broken": "Something went wrong on this page.",
  "failure.unreachable": "The server could not be reached.",
  /** An address naming nobody, which this side will not send. */
  "failure.notAnAddress": "That address does not name anybody here.",
  "failure.unreadable":
    "The server refused this, in a way this side cannot read.",
  /** Stands in for a served code that arrived with no sentence here. */
  "failure.unworded": "The server refused this request.",
  /** Names the developer half without putting it in front of the reader. */
  "failure.disclosure": "Technical detail",
  /**
   * The document's own member names, and worded as them in every catalogue:
   * they are what somebody reading a log or a response body will look for.
   */
  "failure.code": "code",
  "failure.status": "status",
  "failure.detail": "detail",

  /**
   * The rule behind each act, said where a reader meets it: a page they may not
   * open, or a change refused where the control knows what it asked for. Each
   * names the rule and says nothing of the reader. Not below, because nothing
   * here is keyed by a served code; `refusal.ACT_NOT_PERMITTED` is the server's
   * word for the same wall, for where the act is not known.
   */
  "reach.keep_pool":
    "The pool is seen and changed only by a role that may keep it.",
  "reach.grant_estate_role":
    "Estate roles are granted and withdrawn only by a role that may grant them.",
  "reach.keep_group_register":
    "The register of groups is seen and changed only by a role that may keep it.",
  "reach.check_soundness":
    "Soundness is read and checked only by a role that may check it.",
  "reach.read_measurements":
    "Measurements is read only by a role that may read what the estate measures.",
  /** A page of a group the reader is in; one of a group they are not in is missing, not refused. */
  "inGroup.read_membership":
    "A group's members are seen only by a role in it that may see them.",
  "inGroup.change_membership":
    "A group's membership is changed only by a role in it that may change it.",
  "inGroup.author_entry":
    "A group's entries are started, written and submitted only by a role in it that may write one.",
  "inGroup.approve_entry":
    "A group's entries are put into service, and a run's raised ceiling approved or refused, only by a role in it that may approve an entry.",
  "inGroup.revoke_entry":
    "A group's entries are retired, stopped and let go only by a role in it that may revoke one.",
  "inGroup.start_run":
    "A group's runs are started, renamed, stopped, opened again and given a ceiling, and a raise asked withdrawn, only by a role in it that may start one.",
  "inGroup.answer_step":
    "A group's steps are answered, and asked for again, only by a role in it that may answer one.",
  "inGroup.review_at_gate":
    "A group's steps are reviewed, what they give back assured or refused, only by a role in it that may review them.",
  /** Being in any group at all is what reaches My work. */
  "myWork.rule": "My work is open only to somebody in a group.",

  /**
   * What a refusal means to the person who met it. The id after the namespace
   * is the served code itself, so this catalogue is the only list of what can
   * be said about a refusal and there is no second one to keep in step with it.
   *
   * No compiler ties that list to the enum it mirrors, and a constant renamed
   * there would degrade silently to `failure.unworded` here — so what holds the
   * two level is a spec beside the enum, which reads these keys as text.
   *
   * The ones below are stamped on a response that declared no code of its own;
   * any other code stamped that way falls to `failure.unworded`.
   */
  "refusal.BAD_REQUEST": "Some of what was sent was not accepted.",
  "refusal.NOT_FOUND": "That is not here, or is not yours to see.",
  "refusal.INTERNAL": "Something went wrong on the server.",

  /**
   * Said whether nothing was presented or what was presented could not be read.
   * The server answers both alike on purpose, and a sentence naming which of
   * the two it was would hand back what that decision withholds.
   */
  "refusal.NOT_SIGNED_IN": "You are not signed in.",

  "refusal.ACT_NOT_PERMITTED": "This is done only by a role that reaches it.",
  /** Said alike whoever sent it: the rule is about where a request came from. */
  "refusal.ORIGIN_UNVERIFIED":
    "A change is only accepted from this application's own pages.",
  "refusal.BODY_UNUSABLE": "What was sent is not what this takes.",
  "refusal.BODY_SENT_TOO_SLOWLY":
    "What was sent arrived too slowly to be read; send it again.",
  "refusal.SERVICE_BUSY":
    "This is busy with another large request; send it again shortly.",

  "refusal.PEOPLE_SEARCH_UNUSABLE":
    "Type part of a name, or a whole user number, to search.",
  "refusal.USER_NOT_IN_DIRECTORY":
    "Nobody in the directory has that user number.",
  "refusal.PERSON_ALREADY_IN_POOL": "That person is already in the pool.",
  /**
   * What has to go before somebody can leave the pool. The roles and groups
   * are not named here; the person's own panel names them.
   */
  "refusal.PERSON_HOLDS_ESTATE_ROLES":
    "Somebody holding an estate role cannot be taken out of the pool. Withdraw their estate roles first.",
  "refusal.PERSON_IN_GROUPS":
    "Somebody in a group cannot be taken out of the pool until they are in none.",
  "refusal.LAST_ESTATE_ROLE_GRANTOR":
    "Withdrawing this would leave nobody who may grant an estate role.",

  "refusal.GROUP_NAME_UNUSABLE":
    "A group's name is one to 128 characters on one line: no space but single plain ones between words, none at either end, and something in it that shows.",
  "refusal.GROUP_KEY_UNUSABLE":
    "A group's key is two to sixteen English letters and nothing else.",
  /** Said alike whichever case either key was typed in: keys are held in capitals. */
  "refusal.GROUP_KEY_TAKEN": "Another group already holds that key.",
  "refusal.GROUP_NAME_TAKEN": "Another group already has that name.",
  "refusal.PERSON_NOT_IN_POOL": "That person is not in the pool.",
  /**
   * Said alike of a group there is none of and one the reader is in no role
   * of: the server answers both alike, so whoever is not in a group learns
   * nothing of it here.
   */
  "refusal.GROUP_NOT_IN_VIEW": "That group is not in view.",
  "refusal.PERSON_ALREADY_IN_GROUP":
    "That person already holds a role in this group.",
  /** A group always keeps somebody who may change its membership. */
  "refusal.LAST_MEMBERSHIP_CHANGER":
    "Nobody else in this group could change its membership.",
  /** Withholds whether the person is anybody in the pool, which a member of the group may not ask. */
  "refusal.MEMBER_NOT_IN_VIEW": "That person is not a member of this group.",
  "refusal.CURRENCY_NOT_PRICED": "No model is priced in that currency.",

  /**
   * About how something was asked for, never about what it holds: the same
   * sentence whatever was sent, so nothing in it depends on the rows.
   */
  "refusal.LIST_SORT_UNUSABLE": "This list cannot be sorted that way.",
  "refusal.LIST_FILTER_UNUSABLE":
    "That filter is too long, or holds a character that cannot be searched for.",
  "refusal.LIST_CURSOR_UNUSABLE":
    "Your place in this list was lost. Start again from the first page.",
  "refusal.PARAMETER_UNKNOWN":
    "This was asked for in a way it does not understand.",

  /**
   * Withholds whether the row exists, which every other refusal concedes. Only
   * a reader who keeps the pool or grants estate roles meets it: no "yours".
   */
  "refusal.PERSON_NOT_IN_VIEW": "That person is not in the pool.",

  /** A group's library, whose every entry its members may read. */
  "refusal.ENTRY_NOT_IN_VIEW": "That entry is not in this group's library.",
  "refusal.VERSION_NOT_IN_VIEW": "That version is not in this group's library.",
  "refusal.ENTRY_NAME_TAKEN":
    "Another entry of this kind in this group already has that name.",
  "refusal.ENTRY_NAME_UNUSABLE":
    "An entry's name is one to 128 characters on one line: no space but single plain ones between words, none at either end, and something in it that shows.",
  "refusal.ENTRY_PURPOSE_UNUSABLE":
    "What an entry is for is at most 512 characters on one line, with something in it that shows.",
  "refusal.DRAFT_ALREADY_STARTED":
    "This entry already has a version that is a draft or submitted.",
  "refusal.VERSION_STANDING_REFUSES":
    "That version's standing does not admit this.",
  "refusal.APPROVER_WROTE_VERSION": "Nobody approves a version they wrote.",
  "refusal.VERSION_NOT_PINNABLE":
    "Only a version of this group's in service may be pinned.",
  "refusal.VERSION_PINS_RETIRED": "This version pins a version retired since.",
  "refusal.CODE_STEP_NOT_PUBLISHED":
    "Only a code step published to this group may be named.",
  "refusal.STEP_NAME_UNUSABLE":
    "A step's name is one to 63 lowercase English letters, digits and underscores, starting with a letter.",
  "refusal.STEPS_TOO_MANY": "A workflow version holds at most 256 steps.",
  "refusal.BINDINGS_PAST_INPUTS":
    "What fills a step, a case or what the workflow gives back is at most one binding for each field it declares.",
  "refusal.CASE_TERM_REPEATED":
    "No two cases of one route are on the same term.",
  "refusal.CASES_PAST_TERMS":
    "A route holds at most one case for each term the list it chooses by offers, and a fallback.",
  "refusal.CONSTANT_DOES_NOT_FIT":
    "A constant is written as a value is: a number written plainly, with no exponent and never a zero with a minus sign, in at most 38 digits either side of its point, no NUL character, no more than 8,192 characters of text in all, and no more than 1,048,576 characters written out.",
  "refusal.VERSION_CONTENT_DOES_NOT_HOLD":
    "Some of what this version holds does not hold yet. Each place is named.",
  "refusal.INSTRUCTION_UNUSABLE":
    "An instruction is one to 8192 characters with something in it that shows. Lines may be broken, and indented with tabs.",
  "refusal.FIELD_NAME_UNUSABLE":
    "A field's name is one to 63 lowercase English letters, digits and underscores, starting with a letter.",
  "refusal.FIELD_WORDS_UNUSABLE":
    "A field's label is at most 128 characters and its help at most 512, each on one line with something in it that shows.",
  "refusal.FIELD_LIMIT_UNUSABLE":
    "How long a field may be and how many it may hold are whole numbers from 1 to 2147483647, and a confidence is from 1 to 100.",
  "refusal.DECLARATION_TOO_DEEP":
    "A field is held more than 32 deep, or so deep that the names down to it, joined by dots, run past 1023 characters.",
  "refusal.DECLARATION_TOO_LARGE":
    "A half holds at most 256 fields, at every depth together.",
  "refusal.DRAFT_WRITTEN_SINCE_READ":
    "Somebody changed this draft since it was read; nothing was saved.",
  "refusal.LIST_TOO_LARGE":
    "This reference list holds as many terms as a list may already; nothing was added.",
  "refusal.NOTE_UNUSABLE":
    "A note is one to 2048 characters with something in it that shows. Lines may be broken, and indented with tabs.",
  "refusal.PROSE_DIRECTION_CONTROL":
    "What was written holds a direction control, which text sent to a model may not hold.",
  "refusal.PROSE_INVISIBLE_CHARACTER":
    "What was written holds a character that shows nothing, which a term may not hold.",
  "refusal.PROSE_LINE_BREAK_CRLF":
    "What was written breaks its lines with a carriage return and a line feed (CRLF); a line here ends in a line feed alone.",
  "refusal.PROSE_TAG_CHARACTER":
    "What was written holds a tag character, which shows nothing and which text sent to a model may not hold.",
  "refusal.TERM_AT_END":
    "That term is already first or last, so it moves no further that way.",
  "refusal.TERM_MEANING_UNUSABLE":
    "What a term means is one to 512 characters on one line, with something in it that shows.",
  "refusal.TERM_NOT_IN_VIEW": "That term is not in this draft.",
  "refusal.TERM_UNUSABLE":
    "A term is one to 128 characters on one line: no space but single plain ones between words, none at either end, and something in it that shows.",

  /** A run of this group's that the reader may read. */
  "refusal.RUN_NOT_IN_VIEW": "That run is not in view.",
  "refusal.RUN_BENEATH_ANOTHER":
    "A run beneath another is changed only with the run at the top.",
  "refusal.RUN_NAME_UNUSABLE":
    "A run's name is one to 128 characters on one line, with something in it that shows.",
  "refusal.WORKFLOW_NOT_OFFERED":
    "Only a version in service of a workflow of this group's, not stopped, may be started.",
  "refusal.VALUE_DOES_NOT_FIT": "Each value is written as its field takes it.",
  "refusal.CEILING_UNUSABLE":
    "A ceiling is a whole number from one to 9,007,199,254,740,991, written in digits, or none at all.",
  "refusal.CEILING_RAISE_NOT_WAITING": "That raise is not waiting on anybody.",
  "refusal.CEILING_RAISE_ASKED_BY_CALLER":
    "Nobody approves or refuses a raise they asked for.",
  "refusal.CEILING_RAISE_ASKED_BY_ANOTHER":
    "A raise is withdrawn only by whoever asked for it.",

  /** A step of a run the reader may read, and what they do to it. */
  "refusal.STEP_NOT_IN_VIEW": "That step is not in view.",
  "refusal.STEP_MOVED_ON": "That step has moved on since it was read.",
  "refusal.RUN_STOPPED":
    "A stopped run takes no answer, review or try until it is opened again.",
  "refusal.ENTRY_STOPPED":
    "What this step runs, or the workflow itself, is stopped, so no try is made on it until that is let go.",
  "refusal.ASK_AGAIN_NOT_OFFERED":
    "This step's next try is only ever somebody's answer to it.",
  "refusal.CODE_STEP_GIVES_OTHERWISE":
    "What this code step gives back, as this release declares it, no longer matches what the workflow reads from it or the lists this group holds, so it cannot be answered here.",
  "refusal.TRY_SENDING_NOT_OFFERED":
    "Try sending is only for a call to a model that could not be sent: the model turned it away, it was too long for the model, or it is to a model, or a mode of one, that this deployment does not offer.",
  "refusal.REVIEW_NOT_A_PERSONS":
    "Those values wait on the model the step names to review.",
  "refusal.REVIEW_OWN_PRODUCTION": "Nobody reviews what they produced.",
  "refusal.REVIEW_INCOMPLETE":
    "A review decides every value waiting on it, and names nothing else.",
  "refusal.REASON_MISSING": "A refusal, and an answer, say why.",
  "refusal.REASON_UNUSABLE":
    "A reason is prose of one to 2048 characters, with something in it that shows.",
};
